### ISSUE TITLE
Use of Jax-RS for reading the yearbook

### ISSUE THREAD

**Issue by AntonyEnt** [LAntoine/LAMSADE-tools#2]

**Comment by AntonyEnt** [comment]
Reading documentation : https://jax-rs-spec.java.net/

**Comment by js-dev88** [comment]
- try catch
- logger
- javadoc
- import library from Maven

**Comment by js-dev88** [comment]
TODO  
try catch
logger
javadoc maj
test class

**Comment by js-dev88** [comment]
Careful, Jax-RS seems to require log4j for loggers (warning  when the class is launched). 
The architecture is correct and the logger is working. It can be an example for the rest.
the test class is created but empty.

**Comment by js-dev88** [comment]
issue resolved
