### ISSUE TITLE
OM (Mission Order :))

### ISSUE THREAD

**Issue by js-dev88** [LAntoine/LAMSADE-tools#43]
Mission Order and relatives
- create a spreadsheet with User 's informations and Conference's data (user part is done)
see  generateMissionOrder Class

**Comment by js-dev88** [comment]
Capitalize firstname and lastname in getFirstname and getLastname of userDetails class
Mission Order is generated with user details info
TODO: retrieve Conference info from GUI and set the infos in the spreadsheet
TODO : unitary test

**Comment by edoreld** [comment]
What problem is this issue trying to solve? What are you trying to do with Ordres de Mission? I can't tell what this issue is for.

**Comment by js-dev88** [comment]
Done. Waiting for Kevin's Update, issue is closed for the moment
